# Generated by Django 3.1.7 on 2021-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210330_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics'),
        ),
    ]
