# Generated by Django 3.1.7 on 2021-03-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authol',
            new_name='author',
        ),
    ]
