# Generated by Django 3.1.7 on 2021-03-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im_blog', '0002_auto_20210324_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
